apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hpa-example
  name: hpa-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-example
  strategy: {}
  template:
    metadata:
      labels:
        app: hpa-example
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        name: hpa-example
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-example
spec:
  selector:
    app: hpa-example
  ports:
  - port: 80
    targetPort: 80